### ISSUE TITLE
Upgrade frontend to latest stable version of Angular Material

### ISSUE THREAD

**Issue by Ignigena** [mybethel/my.bethel.io#59]
### Details

Currently using an outdated and buggy version. Need to upgrade to the latest stable version as it's hit a 1.0 release cycle.

### Requirements

* All pages upgraded to latest Material version
* Where possible move UI elements to Components in Angular

### Development Tasks

- [ ] general upgrade of interface structure
- [ ] fine tuning of login and accept invite screens
- [ ] fine tuning of home page
- [ ] fine tuning of podcast overview
- [ ] fine tuning of podcast detail
- [ ] fine tuning of podcast wizard
- [ ] fine tuning of settings panel
- [ ] fine tuning of beta lockout screen
