### ISSUE TITLE
As a ministry I'd like the ability to enter my CC information from my settings page, so that I can get billed for my platform usage.

### ISSUE THREAD

**Issue by Josh-Mosh** [mybethel/my.bethel.io#62]
### Details

This information will be stored in Stripe, so a Stripe user/customer will be created for each ministry. Plans will be assigned to this customer and we can set it to bill monthly. stripe.com/docs

### Requirements

* Only one credit card will/can exist per ministry
* Only the ministry's "billing contact" role should be able to edit this information (make separate story)
* Stripe will create a customer ID which we can reference in the ministry model
* This story will include the ability to edit existing credit card info

### How to Demo

1. Log in as user with no credit card info entered
1. Go to settings > subscription and billing
1. See form to enter new credit card info
1. Submit new credit card info
1. Confirm new customer is created in stripe and success dialog is shown
1. Click to edit credit card info
1. Enter new card info and submit
1. Confirm Stripe customer is updated and success dialog is shown in Bethel

### Development Tasks

- [ ] Investigate Stripe's "Checkout" which provides a prebuilt payment form. https://stripe.com/docs/recipes/subscription-signup or https://stripe.com/docs/recipes/subscription-signup
- [ ] Confirm stripe account is accessible by all Bethel team members
- [ ] Create credit card form on subscription and billing page (based on whether CC info is already entered or if there is none.
- [ ] Hook up stripe POST requests so new customers can be created
- [ ] Add Bethel contact link informing users of how to cancel their account
- [ ] Build ability to submit new CC to stripe to replace existing
