### ISSUE TITLE
As a ministry I'd like to be able to create an account without having to request a Beta invite.

### ISSUE THREAD

**Issue by Ignigena** [mybethel/my.bethel.io#64]
### Details

Users should be able to create an account by visiting my.bethel.io and clicking Register and by clicking through getbethel.com

### Requirements

- Protect against bots with Recaptcha
- E-mail confirmation before account can be used (re-use the existing invite token functionality)
- Ask for ministry details and personal details (maybe re-use some of the survey fields from current form)
- Use Google Places autocomplete when user enters the ministry name
- If an address is available, use this to create their first location
- Inform users they will be charged for use and link to pricing page for questions

### How to Demo

1. Visit my.bethel.io as an anonymous user
1. Click the register button and fill out the form
1. Verify that a confirmation e-mail is sent to the user
1. Click the confirmation link
1. Verify the user is logged in and can set their password

### Development Tasks

- [ ] implement registration form on frontend (name, e-mail, ministry name)
- [ ] integration with google places to autocomplete the ministry name
- [ ] if address is available, create a location automatically
- [ ] google recaptcha support
- [ ] add new "confirm your address" e-mail from the invite e-mail process
- [ ] when form is submitted, immediately send confirmation link
- [ ] look into repurposing invite acceptance screen with invite code section hidden
