### ISSUE TITLE
As a user I would like the ability to invite other users to my ministry so that I can share access.

### ISSUE THREAD

**Issue by Ignigena** [mybethel/my.bethel.io#65]
### Details

Will not include multiple levels of permissions. All users will have the same permissions. Will not accomodate for users on multiple ministries. If the user that is being invited already has an account, we will make the inviter contact Bethel support for now.

### Requirements

* Allow invites with a name and e-mail address. This will create a new user account associated to the ministry.
* Re-use the logic from the staff invite process for this.
* Validate whether the user already exists and force contacting Bethel if there is a duplicate.

### How to Demo

1. Log in as a user
2. Visit the Settings > My Team page
3. Click invite user button
4. Fill in name and e-mail address
5. Verify that invite e-mail is sent
6. Accept invite and verify that user is part of the same ministry
7. Repeat process with a user that already exists in the system
8. Verify that warning is shown directing user to contact support

### Development Tasks

- [ ] implement invite button and form on Settings > My Team page
- [ ] default ministry association to the current ministry
- [ ] validate the user does not already exist and show an error if so
- [ ] re-use the staff invite functionality to fire off the e-mail
- [ ] re-theme the invite e-mail to include the name of the person that invited them
